apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "custom-model"
  annotations:
    autoscaling.knative.dev/target: "1"
spec:
  predictor:
    logger:
      mode: all
      url: http://message-dumper.default/  
    containers:
      - name: "kserve-container"
        image: shreeharivl/custom-model:v1.6
        imagePullPolicy: IfNotPresent
